### ISSUE TITLE
/dev/ttys000 is not always correct

### ISSUE THREAD

**Issue by kevinreedy** [fntlnz/doenter#1]
You might need add add some more logic. https://github.com/fntlnz/doenter/blob/master/main.go#L47 points to `/dev/ttys000`. On my machine, it's `/dev/ttys003`. Looks like `~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty` may always be a symlink to the correct one.

**Comment by atosatto** [comment]
@kevinreedy you are perfectly right! 
As you can see, I've pushed a PR implementing your suggestion.
Thank you very much for the feedback!

**Comment by fntlnz** [comment]
Thank you both @kevinreedy and @atosatto  . The PR has been merged #3
