### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by jmreicha** [fntlnz/doenter#2]
Following the README I installed via curl but get the following message when I run `doenter`:

```
panic: runtime error: slice bounds out of range

goroutine 6 [running]:
panic(0xeff20, 0xc82000a0b0)
    /usr/local/go/src/runtime/panic.go:481 +0x3e6
main.read(0x2491e8, 0xc820012240)
    /go/src/github.com/fntlnz/doenter/main.go:18 +0x232
created by main.main
    /go/src/github.com/fntlnz/doenter/main.go:54 +0x19b
```

**Comment by atosatto** [comment]
Hi @jmreicha!

Could you please check if Docker is listening on `/dev/ttys000` running 
`ls -la ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty`?

Right now doenter it's pretty hacky, but we are gonna definitively improve it! 😄

**Comment by fntlnz** [comment]
@jmreicha Thanks for reporting 💛  Now it's fixed

To upgrade:

```
curl -L https://github.com/fntlnz/doenter/releases/download/0.1.1/doenter > /usr/local/bin/doenter
chmod +x /usr/local/bin/doenter
```
