### ISSUE TITLE
No way to leave login

### ISSUE THREAD

**Issue by jmreicha** [fntlnz/doenter#5]
Is there a way to cleanly exit out of `doenter` from the login prompt (ctl-c doesn't work)?  Right now I have to close the shell I am in and then force kill the process to get it to exit.

**Comment by atosatto** [comment]
Hi @jmreicha. 
Which version of `doenter` are you using?
In commit dd6d00b @fntlnz has implemented a nice feature to exit without killing the process

``` bash
./doenter                                                            !10078
Send two times Ctrl-c (SIGINT) in order to leave doenter

Welcome to Moby alpha
Kernel 4.4.14-moby on an x86_64 (/dev/ttyS0)

                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/

moby login:
```

Probably we should ask @fntlnz to tag a new release. :laughing:

**Comment by fntlnz** [comment]
@jmreicha @atosatto I released that 🎉 

https://github.com/fntlnz/doenter/releases/tag/0.1.2

There's probably a better way to handle this rather than using SIGINT, when I'll figure that this is probably going to change

**Comment by jmreicha** [comment]
Just grabbed the newest release and it is working.  Thanks!
